### ISSUE TITLE
Florence net issue: calling view or fetching token metadata 

### ISSUE THREAD

**Issue by BodySplash** [tqtezos/TZComet#44]
I have this FA2 for testing purposes on florence :  KT1C7xFhKsnXPzD9hAQUBpGFuXChXd3nuE3a

I have pretty much the same on edo also : KT1XMnfo3J9fR6SbPkvabqsTiNWGo3a8dWJh 

On edo, with TZComet, everything works fine (extracting metadata, calling views, exploring tokens), but on florence, if I try to call a view, or explore tokens, I always end up with this error :
```
failed with with return code 400:
Failed to parse the request body: Missing object field balance
```
when it calls the `run_code` endpoint.

I don't know if it's a Node issue or a TzComet issue, so sorry if I'm generating noise here.

**Comment by smondet** [comment]
It should all work on `/staging`:  https://tzcomet.io/staging/#/explorer%3Fgo%3Dtrue%26explorer-input%3DKT1C7xFhKsnXPzD9hAQUBpGFuXChXd3nuE3a

**Comment by BodySplash** [comment]
Seems to work perfectly fine. Do you want me to close the issue ?

**Comment by smondet** [comment]
I'll close when I merge & deploy in prod :+1:
