### ISSUE TITLE
Cannot check token metadata for token ids >INT32

### ISSUE THREAD

**Issue by damian0815** [tqtezos/TZComet#71]
I'm trying to get the token metadata for two tokens on my contract, `10000000000` and `10000000001` but TZComet's UI seems to be limiting me to Int32 token ids. Since FA1.2/FA2 uses NAT token ids, this ought to work.

to reproduce: go to https://tqtezos.github.io/TZComet/#/explorer%3Fgo%3Dtrue%26explorer-input%3DKT1Cu1o3JFwLRHkgS9R4rAf9Ph9MZERtPhMd , expand "explore tokens", un-tick "Use the all_tokens off-chain-view", attempt to type `10000000000` in the Search Parameters box. 

Note error message: `Wrong format: 10000000000: The string "10000000000" is not an integer.`

**Comment by damian0815** [comment]
Probably related: leaving "Use the all_tokens off-chain-view" ticked gives the following error after enumerating the tokens: `Error: Exception:
Z.Overflow`

**Comment by smondet** [comment]
Thanks for the report

#72 fixes this in all cases except the "printer language"

**Comment by smondet** [comment]
FYI this fix just got deployed to tzcomet.io: https://tzcomet.io/#/explorer%3Fgo%3Dtrue%26explorer-input%3DKT1Cu1o3JFwLRHkgS9R4rAf9Ph9MZERtPhMd

(sorry it took us a while, we had to deal with the transfer of the repo/deployment)
